# Generated by Django 2.1.1 on 2018-11-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_biometrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
