# Generated by Django 2.1.1 on 2018-11-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_auto_20181112_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='biometric',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='biometric',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
