# Generated by Django 2.1.1 on 2018-12-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181210_2150'),
        ('biometrics', '0003_auto_20181113_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometric',
            options={'ordering': ('profile',)},
        ),
        migrations.RemoveField(
            model_name='biometric',
            name='user',
        ),
        migrations.AddField(
            model_name='biometric',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_biometrics', to='profiles.BaseProfile'),
        ),
    ]
