# Generated by Django 2.1.1 on 2018-09-24 08:19

import albums.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20180924_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_albums', to='profiles.BaseProfile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=albums.models.photo_upload_path)),
                ('caption', models.TextField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_photos', to='albums.Album')),
            ],
            options={
                'ordering': ('-is_primary', '-created'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'profile')},
        ),
    ]
