# Generated by Django 2.1.1 on 2018-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.PositiveIntegerField(choices=[(18798, 'Profile Photos'), (9392, 'Cover Photos'), (76930, 'Generic Album')], default=76930),
        ),
    ]
