# Generated by Django 2.1.1 on 2018-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20180927_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
