PROFILE_PHOTO_ALBUM = 18798
COVER_PHOTO_ALBUM = 9392
GENERIC_ALBUM = 76930

GENERIC_ALBUM_CHOICES = (
    (PROFILE_PHOTO_ALBUM, "Profile Photos"),
    (COVER_PHOTO_ALBUM, "Cover Photos"),
    (GENERIC_ALBUM, "Generic Album")
)
